# Generated by Django 3.2.3 on 2021-05-29 17:50

from django.db import migrations, models
import suggestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('sender', models.IntegerField()),
                ('reciever', models.IntegerField()),
                ('file', models.TextField()),
                ('upload_files', models.FileField(null=True, upload_to=suggestion.models.get_file_path, verbose_name='파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
            ],
            options={
                'db_table': 'suggestion',
                'managed': False,
            },
        ),
    ]
