# Generated by Django 3.2.3 on 2021-05-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('sender', models.IntegerField()),
                ('reciever', models.IntegerField()),
                ('file', models.TextField()),
            ],
            options={
                'db_table': 'suggestion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('user_num', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=32, null=True)),
                ('user_password', models.CharField(blank=True, max_length=64, null=True)),
                ('user_name', models.CharField(blank=True, max_length=12, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('user_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_department', models.CharField(blank=True, max_length=30, null=True)),
                ('user_position', models.CharField(blank=True, max_length=30, null=True)),
                ('user_rank', models.IntegerField(blank=True, null=True)),
                ('user_profile', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('user_age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userinfo',
                'managed': False,
            },
        ),
    ]
