# Generated by Django 3.2.3 on 2021-05-29 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0002_suggestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
