# Generated by Django 3.2.3 on 2021-05-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0004_uploadfilemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFileModel',
        ),
    ]
